FROM fedora:@FEDORA_VERSION@
MAINTAINER Mikkel Kruse Johnsen <mikkel@xmedicus.com>

RUN rpm -Uvh http://yum.gsharpkit.org/gsharpkit/fedora-@FEDORA_VERSION@-x86_64/RPMS/GSharpKit-release-@VERSION@-@RELEASE@.fc@FEDORA_VERSION@.noarch.rpm

RUN rm -f /etc/rpm/macros.image-language-conf

RUN dnf -y --exclude darwinx* install sudo hunspell-da hunspell-en-GB hunspell-en-US python msitools mono-core-@MONO_VERSION@ mono-extras-@MONO_VERSION@ mono-locale-extras-@MONO_VERSION@ mono-data-@MONO_VERSION@ mono-data-sqlite-@MONO_VERSION@ mono-web-@MONO_VERSION@ mono-wcf-@MONO_VERSION@ mono-mvc-@MONO_VERSION@ mono-winfxcore-@MONO_VERSION@ GSharpKit-sdk GSharpKit-sdk-mingw-devel GSharpKit-sdk-mingw && dnf clean all && rm -rf /var/cache/dnf

RUN mkdir /usr/i686-w64-mingw32/sys-root/mingw/share/myspell ; cp /usr/share/myspell/da_DK.aff /usr/share/myspell/da_DK.dic /usr/share/myspell/en_GB.aff /usr/share/myspell/en_GB.dic /usr/share/myspell/en_US.aff /usr/share/myspell/en_US.dic /usr/i686-w64-mingw32/sys-root/mingw/share/myspell/
RUN mkdir /usr/x86_64-w64-mingw32/sys-root/mingw/share/myspell ; cp /usr/share/myspell/da_DK.aff /usr/share/myspell/da_DK.dic /usr/share/myspell/en_GB.aff /usr/share/myspell/en_GB.dic /usr/share/myspell/en_US.aff /usr/share/myspell/en_US.dic /usr/x86_64-w64-mingw32/sys-root/mingw/share/myspell/

