#!/bin/sh
if [ -f /Library/LaunchAgents/org.freedesktop.dbus-session.plist ]; then
	INSTALLER_USER=$(stat -f '%Su' $HOME)
        sudo -u $INSTALLER_USER launchctl unload -w /Library/LaunchAgents/org.freedesktop.dbus-session.plist
fi

