FROM fedora:@FEDORA_VERSION@
MAINTAINER Mikkel Kruse Johnsen <mikkel@xmedicus.com>

RUN dnf -y install http://yum.gsharpkit.org/gsharpkit/fedora-@FEDORA_VERSION@-x86_64/RPMS/GSharpKit-release-@VERSION@-@RELEASE@.fc@FEDORA_VERSION@.noarch.rpm

RUN rm -f /etc/rpm/macros.image-language-conf

RUN dnf -y install GSharpKit-sdk-@FRAMEWORK@-darwinx && dnf clean all && rm -rf /var/cache/dnf

RUN mkdir -p /Library/Frameworks/GSharpKit/share/hunspell ; cp /usr/share/hunspell/da_DK.aff /usr/share/hunspell/da_DK.dic /usr/share/hunspell/en_GB.aff /usr/share/hunspell/en_GB.dic /usr/share/hunspell/en_US.aff /usr/share/hunspell/en_US.dic /Library/Frameworks/GSharpKit/share/hunspell/

