FROM fedora:@FEDORA_VERSION@
MAINTAINER Mikkel Kruse Johnsen <mikkel@xmedicus.com>

RUN rpm -Uvh http://yum.gsharpkit.org/gsharpkit/fedora-@FEDORA_VERSION@-x86_64/RPMS/GSharpKit-release-@VERSION@-@RELEASE@.fc@FEDORA_VERSION@.noarch.rpm

ADD packages/*.noarch.rpm /tmp/
RUN rpm -Uvh --nodeps --ignoreos /tmp/*.noarch.rpm && rm -f /tmp/*.noarch.rpm

RUN dnf -y install python2.7 hunspell-da hunspell-en-GB hunspell-en-US GSharpKit-runtime GSharpKit-sdk GSharpKit-sdk-darwinx && dnf clean all && rm -rf /var/cache/dnf
RUN ln -s /usr/share/dotnet/sdk /usr/lib64/dotnet/sdk

RUN mkdir /Library/Frameworks/GSharpKit/share/hunspell ; cp /usr/share/hunspell/da_DK.aff /usr/share/hunspell/da_DK.dic /usr/share/hunspell/en_GB.aff /usr/share/hunspell/en_GB.dic /usr/share/hunspell/en_US.aff /usr/share/hunspell/en_US.dic /Library/Frameworks/GSharpKit/share/hunspell/

