FROM fedora:@FEDORA_VERSION@
MAINTAINER Mikkel Kruse Johnsen <mikkel@xmedicus.com>

RUN rpm -Uvh http://yum.gsharpkit.org/gsharpkit/fedora-@FEDORA_VERSION@-x86_64/RPMS/GSharpKit-release-@VERSION@-@RELEASE@.fc@FEDORA_VERSION@.noarch.rpm

RUN dnf -y --exclude darwinx* install sudo rpm-build nHapi NHapiTools nuget netstandard mono-core-@MONO_VERSION@ mono-extras-@MONO_VERSION@ mono-locale-extras-@MONO_VERSION@ mono-data-@MONO_VERSION@ mono-data-sqlite-@MONO_VERSION@ mono-web-@MONO_VERSION@ mono-wcf-@MONO_VERSION@ mono-mvc-@MONO_VERSION@ mono-winfxcore-@MONO_VERSION@ GSharpKit-sdk && dnf clean all && rm -rf /var/cache/dnf

RUN mkdir -p /root/rpm/SPECS ; mkdir -p /root/rpm/SOURCES ; mkdir -p /root/rpm/BUILD ; mkdir -p /root/rpm/RPMS ; mkdir -p /root/rpm/SRPMS ; mkdir -p /root/rpm/BUILDROOT ; echo "%_topdir /root/rpm" > /root/.rpmmacros 
